name: Build faps
on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
    inputs:
      sdk-channel:
        description: 'SDK channel to use'
        required: true
        default: 'rc'
        type: choice
        options:
          - 'rc'
          - 'release'
          - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        with:
          sdk-channel: ${{ github.event.inputs.sdk-channel || 'rc'}}
          task: setup

      - name: Build & lint all apps
        run: |
          BUILD_FAILED=0
          for appdir in $( dirname $( find . -name application.fam ) ) ; do
            echo "Building in $appdir"
            pushd $appdir
            if ! ufbt build faps ; then
              BUILD_FAILED=1
              echo "::error::Failed to build $appdir"
            fi
            popd
          done
          rm -rf dist || true && mkdir dist
          for fapfile in $( find . -name "*.fap" ) ; do
            cp $fapfile dist/
          done
          if [ $BUILD_FAILED -ne 0 ] ; then
            echo One or more apps failed to build
            exit 1
          fi

      - name: Upload all .fap files
        uses: actions/upload-artifact@v3
        with:
          name: faps
          path: dist/*.fap
